[package]
name = "reqwest-scraper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
itertools = "0.13"
jsonpath_lib = "0.3"
nom = "7.1.3"
reqwest = { version = "0.12", features = ["json"] }
scraper = "0.19"
serde = "1.0"
serde_json = "1.0"
skyscraper = "0.6"
thiserror = "1.0"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
