name: Publish

on:
  push:
    branches: ["master"]
    paths:
      - "reqwest-scaper-macros/src/*"
      - "reqwest-scaper-macros/Cargo.toml"
      - "src/*"
      - "Cargo.toml"
  pull_request:
    branches: ["master"]
  workflow_dispatch:
    inputs:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependency
        run: cargo install cargo-workspaces
      - name: Build
        run: cargo build --workspace --verbose
      - name: Run tests
        run: cargo test --workspace --verbose
      - name: Run Publish
        run: cargo ws publish --token=${{secrets.CARGO_TOKEN}}
